# Faceting

**Learning objectives:**

- Facet wrap
- Facet grid
- Controlling scales
- Missing faceting variables
- Grouping vs. faceting
- Continuous variables


## Facets
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
mpg2 <- subset(mpg, cyl != 5 & drv %in% c("4", "f") & class != "2seater")
```

```{r}
base <- ggplot(mpg2, aes(displ, hwy)) + 
  geom_blank() + 
  xlab(NULL) + 
  ylab(NULL)

mpg2%>%count(class)

base + facet_wrap(~class, ncol = 3)
base + facet_wrap(~class, ncol = 3, as.table = FALSE)
```


```{r}
base + facet_wrap(~class, nrow = 3)
base + facet_wrap(~class, nrow = 3, dir = "v")
```



```{r}
base + facet_grid(. ~ cyl)
base + facet_grid(drv ~ .)
```
```{r}
base + facet_grid(drv ~ cyl)
```


```{r}
p <- ggplot(mpg, aes(cty, hwy)) + 
  geom_abline() +
  geom_jitter(width = 0.1, height = 0.1) 
p + 
  facet_grid(drv ~ cyl)
  facet_wrap(~cyl)

```



```{r}
p+ 
  facet_wrap(~cyl, scales = "free_y")
```


```{r}
economics_long%>%count(date)
```


```{r}
ggplot(economics_long, aes(date, value)) + 
  geom_line() + 
  facet_wrap(~variable, scales = "free_y", ncol = 1)
```


```{r}
mpg2$model <- reorder(mpg2$model, mpg2$cty)

mpg2$manufacturer <- reorder(mpg2$manufacturer, -mpg2$cty)

ggplot(mpg2, aes(cty, model)) + 
  geom_point() + 
  facet_grid(manufacturer ~ ., scales = "free", space = "free") +
  theme(strip.text.y = element_text(angle = 0))
```


```{r}
df1 <- data.frame(x = 1:3, y = 1:3, gender = c("f", "f", "m"))
df2 <- data.frame(x = 2, y = 2)
```
```{r}
ggplot(df1, aes(x, y)) + 
  geom_point(data = df2, colour = "red", size = 2) + 
  geom_point() + 
  facet_wrap(~gender)
```

```{r}
df <- data.frame(
  x = rnorm(120, c(0, 2, 4)),
  y = rnorm(120, c(1, 2, 1)),
  z = letters[1:3]
)

ggplot(df, aes(x, y)) + 
  geom_point(aes(colour = z))
```

```{r}
ggplot(df, aes(x, y)) + 
  geom_point(aes(color=z)) + 
  facet_wrap(~z)
```

```{r}
df_sum <- df %>% 
  group_by(z) %>% 
  summarise(x = mean(x), y = mean(y)) %>%
  rename(z2 = z)


ggplot(df, aes(x, y)) + 
  geom_point() + 
  geom_point(data = df_sum, aes(colour = z2), size = 4) + 
  facet_wrap(~z)
```

```{r}
df2 <- dplyr::select(df, -z)

ggplot(df, aes(x, y)) + 
  geom_point(data = df2, colour = "grey70") +
  geom_point(aes(colour = z)) + 
  facet_wrap(~z)
```


```{r}
age<-seq(18,60,1)
id <- seq(1,42,1)
my_df <- as.data.frame(cbind(id,age))

my_df %>% mutate(age_cat=cut_interval(age,length=5))%>%head()
```





```{r}
# Bins of width 1
mpg2$disp_w <- cut_width(mpg2$displ, 1)
# Six bins of equal length
mpg2$disp_i <- cut_interval(mpg2$displ, 6)
# Six bins containing equal numbers of points
mpg2$disp_n <- cut_number(mpg2$displ, 6)

plot <- ggplot(mpg2, aes(cty, hwy)) +
  geom_point() +
  labs(x = NULL, y = NULL)
plot + facet_wrap(~disp_w, nrow = 1)
```






## Meeting Videos







### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
  <summary> Meeting chat log </summary>
  
```
```
</details>
