on:
  pull_request:
    branches: main
  workflow_dispatch:

name: pr_check

jobs:
  bookdown:
    name: pr_check_book
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), "r-depends.rds")
        shell: Rscript {0}
      
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r4ds_bookclub-${{ hashFiles('DESCRIPTION') }}-${{ hashFiles('r-depends.rds') }}
          restore-keys: r4ds_bookclub-
          
      - name: Install dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
        shell: Rscript {0}

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
